---
title: Publication list
date: 2026-06-27
categories:
---

I need to have it written down somewhere. One thing I have learned from this review is that I have not published anything in a long, long time. If I was still in academia, people would think I was dead.


2019
Robust and secure AI: A primer for the c-suite with M. Kuperholz and C. Lee

2017
Digital Productivity: Key Issues from the Literature, joint work with Paul Paterson and Tony Wiskich, February 2017.

2016
An Introduction to Unlisted Investments, The Constant Investor, September 23.

Bonds and Bond Funds: A Long Running Bull Market, The Constant Investor September 23.

Introducing Peer to Peer and Marketplace Lending, The Constant Investor, October 1.

Investing in Unlisted Infrastructure, The Constant Investor, October 21.

Introduction to REITs, The Constant Investor, October 28.

What is Venture Capital?, The Constant Investor, December 9.

Regional Telecommunications Database, coauthored with K. Haigh. Internal report, Department of Communications, December 16.

Small/Microcaps and VC: What are the differences?, The Constant Investor, December 22.

Unlisted Gems: The Wrap Up (An Interview with Victor Yeung), The Constant Investor, December 22.

Interest Rates Rising: Unlisted Gems, The Constant Investor, December 22.

2015
Tongan Early Grade Reading Assessment: Baseline Survey Report, World Bank Report.

“Evaluation of two types of glucose sensor for use with a real-time continuous glucose monitor in dogs and cats,” coauthored with W. Agnew, Australian Veterinary Practitioner 45(4) December 2015, p. 146-152.

Evaluating the Enhanced Bushfire Management Program: A Study by Rex Analytics, internal report commissioned by the National Parks and Wildlife Service.

2014
Western Highlands Province Early Grade Reading Assessment (EGRA) Survey, 2013 Diagnostic Results Report, World Bank Report, coauthored with M. Machuca-Sierra.

Laos Early Grade Reading Assessment, 2012 Baseline Report, World Bank Report, coauthored with M. Machuca-Sierra.

East New Britain (ENB) Early Grade Reading Assessment (EGRA) Survey, 2012 Diagnostic Results Report, World Bank Report, coauthored with M. Machuca-Sierra.

National Capital District (NCD) Early Grade Reading Assessment (EGRA) Survey, 2012 Diagnostic Results Report, World Bank Report, coauthored with M. Machuca-Sierra.

Madang Early Grade Reading Assessment (EGRA) Survey, 2011 Diagnostic Results Report, World Bank Report, coauthored with M. Machuca-Sierra.

2009
“Panel Unit Root Tests in the presence of Cross-sectional Dependence: Finite Sample performance and an Application”, with A.R. Tremayne and K.Hadri, The Econometrics Journal, 12, 340-366.

2008
On the Specificity and Performance of Panel Unit Root Tests, Ph.D. thesis. Supervisor: A. R. Tremayne.

2007
A Panel Stationarity Test for Series with breaks in Either Level or Trend, a working paper presented at the Econometrics Society of Australasia Meeting, July 2007.

A Panel Unit Root Test for a Fractionally Integrated Alternative, a presentation to the Statistical Society of Australia J.B. Douglas Postgraduate Award (joint winner).
