---
title: 'Beyond syntax, towards subculture: on the power and potentiality of deep open
  source communities'
author: Steph
date: '2018-05-17'
slug: beyond-syntax-towards-subculture-on-the-power-and-potentiality-of-deep-open-source-communities
categories:
  - community
tags:
  - talks
---

# Introduction

R is a dynamic, vibrant programming language, going from strength to strength. Originally created by Ihaka and Gentleman in the 1990s, what was a niche experimental language is now in mainstream world-wide usage across many disciplines and domains (Ihaka, 1998).

One thing that Ihaka and Gentleman may not have intended at the time was the fact that R is no longer _just_ a programming language. It's developing into a distinct subculture at the intersection of multiple different fields and domains. This places it in a unique position, both to benefit from those fields and domains and to influence them.

This piece argues that not only is R a developing subculture, that being a subculture it can transmit and develop ideas that have a fundamental economic value beyond the coded output it enables. This piece also argues that not only does R as a subculture engender _value_, it creates, develops and demands _values_. A subculture developing in R does not just develop and transmit _ideas_, it transmits an _ideaology_, one that has the potential to reach well beyond the fields and domains of its userbase.

# Not just a language

R is a programming language with two decades of development. In parallel to that programming development, community development has not only kept pace, but expanded rapidly in recent years. The R community is not bounded by any single institution, group or communication platform. While there are large and distinct groups such as ROpensci, R-Ladies and user groups on every continent (with the possible exception of Antarctica, but give them time) in addition to diverse Twitter and StackOverflow communities: none of these wholly encompass the R community.

These communities, however, share commonalities and crossovers that go beyond the programming language itself. They share distinctive patterns of behaviour, beliefs and mores. These should not be construed as a wholly _homogeneous_ set of beliefs and behaviours: indeed, there are many differences between them. Anheier et al. (2009) note that subcultures can exist at all levels of organisations. In other words, [xkcd was right, it's fractal all the way down](https://xkcd.com/1095/). However, they share distinctive traits that tie them together. 

If we take the definition of a subculture as per Hodkinson (2012), these distinctive traits are _extra-ordinary in their location within the parameters and environment of unusually concentrated and often defiant communities centred on sets of styles and practices which, in some respects, are spectacular and distinctive and are understood as such both by insiders and outsiders._ In the context of R, these are distinctive traits applied by others collectively _("the R community is ...")_ as well as proudly championed in the community, for example, R's own language quirks, notably championed by its assignment operator <-.

The elements of the shared R lifeworld include:

__Shared institutions.__ There are a number of institutions that R users regularly share with, participate in or benefited by. These include institutions critical to the functioning of R as a programming language, such as the R Core group, CRAN (Centralised R Archive Network), the R Journal and the R Foundation. However, participants in the developing subculture are not limited to these institutions: many R users attend local meetups and/or are involved in a remote community either through Twitter, StackOverflow or some other platform. Others in addition may identify with certain groups or ideologies such as R-Ladies, the Tidyverse (a complex subcultural phenomenon in itself) or other community, like the R for Data Science learning community.

__Distinct philosophical and well developed ideaological concepts__. While not espoused or recognised by every member of the community: many members grapple with, embrace or dispute certain philosophies (most notably _'the tidyverse'_), they nonetheless engage with it. Intellectual constructs like the _layered grammar of graphics_ (Wickham, 2010) or the _grammar of data manipulation_ (Wickham et al., 2017) contribute to overall meta constructs of programming and data agency. Indeed, there is a substantial differential of opinon within the developing subculture, which paralells the experience Coleman (2012) observed among 'hackers' in the Debian project:

 _Once we recognise the intimate connection between hacker ethics and liberal commitments *and* the diversity of ethical positions, it is clear that hackers provide less of a unitary and distinguishable ethical position, and more of a mosaic and interconnected, but at times divergent ethical principles._ 

__Content developed for and by the subculture__. The developing subculture produces more content than code for the use of analysts and analysis produced by R code. The developing subculture produces, both for its own consumption and those outside of it:

__Visualisation as art:__ both deliberately (see for example [the R Graph Gallery, Holtz (2017)](https://www.r-graph-gallery.com/portfolio/data-art/) or [Flowing Data (Yau, 2018)](http://flowingdata.com)), and accidentally, shared for appreciative purposes (see for example [accidental aRT (Woo and Mudrak 2018)](http://accidental-art.tumblr.com)).

__Analysis for entertainment and general education:__ for example Robinson's (2016, 2017) [analysis of Trump's tweets](http://varianceexplained.org/r/trump-tweets/) and [Meek and Averick (2017)](https://archervisualization.herokuapp.com) (although the site was built in D3, analysis was also conducted in R).

__Extensive educative materials and communities:__ both for R, the programming language (see for example Bocek (2018), Maegan (2018) among many others), for the dynamic package sharing system, [such as Silge (2017)](https://juliasilge.com/blog/navigating-packages/) and for navigating the community itself, [such as Ellis (2017)](https://ropensci.org/blog/2017/06/23/community/).

__Meta cultural content:__ created for the purpose of alerting the subculture to these resources, such as [R-Bloggers](https://www.r-bloggers.com), [R Weekly](https://www.rweekly.org), and others of more formality such as the R Journal. 
    
This developed lifeworld is not unique to R as a developing subculture among programming languages. The seminal work of Coleman (2012) first noted the development of a rich open source subculture within the Debian project. Coleman noted in particular the interplay between two competing ideaologies, those of individualism and collectivism, within the 'hacker' subculture, as exemplified by the Debian project.

She noted: _The belief in the value of individuality coupled with the constant need for the help of other hackers points to a subtle paradox that textures their social world. The tension between individualism and collectivism, in particular, is negotiated through the extremely well-developed and common penchant that hackers have for performing cleverness, whether through technological production or humor_

A point which many participants in the R community will find familiar: particularly as to the common occurence of cleverness through technological production and humour _at the same time_ (see for example Averick and Meeks 2017).

Does a distinct developing R subculture matter? If so, what does it _mean_? 

# With subculture comes value

A programming subculture is more than just syntax: it's a confluence of institutions, informal and otherwise, inputs and a repeatable cycle of output and value generation. The development of this subculture is driving the development of R, the programming language and in reverse the same is true.

The existence of a developing subculture brings value to the process of creation that extends beyond programmers coding alone and in teams. A subculture absorbs ideas from the outside, sets them to compete with each other, evolves them and generates new ones. This process, an evolutionary tourney of _ideas_ has a real and intrinsic value.

The fact that R as a developing subculture has a unique array of inputs is not surprising. This subculture is at the intersection of a very broad array of fields and provides a communication medium for them, as well as a marketplace for the exchange of ideas. 

While software developers are powering the development of the language, many of them come from non-traditional software engineering backgrounds, or no software engineering background at all.

Users (as distinct to _creators_ of R the programming language) of R are even more diverse: while the language was intended as a statistical one, it now has scientific, engineering, economic applications, as well as important humanities and business ones.

However, it is the array of outputs from this developing subculture that is truly extraordinary. These could be roughly divided into three, non-exclusive, not necessarily consecutive stages:

__First stage outputs:__ Improvements and additions to R itself. Packages, developments to the R base, integrated development environments (IDEs) etc.

__Second stage outputs:__ Scientific, statistical and humanities work built in part using first stage outputs. The development of new statistical, data science or other scientific techniques, algorithms and models.

__Third stage outputs:__ Work that uses these scientific and other research outputs to create other objects of value in the community - business uses, government use, applied scientific research, education, health etc.

Clearly there is an interplay between stages and being neither consecutive or even exhaustive, one piece of work can encompass all three stages.

The fact that open source has _value_ is not new, e.g. Debian, Microsoft's opposition to _FOSS_. But it's not just the technology that is being created that is valuable: it's an evolutionary tourney of ideas that a subculture gives rise to.

Being at the intersection of multiple academic disciplines (statistics, ecology, biology, economics, engineering, computer science, sociology, politics to name a few), schools of thought (e.g. sciences, business, humanities) as well as practioners (academics, students, business, government) means an incredible confluence of ideas generated by this developing subculture.

These compete with and interact with one another, developing nuances, branches and new ideas themselves. This is inherently valuable.

The value that's being driven by this tourney of ideas can be considered in three different types as a rough typology:

__Methodological sharing.__ New methodologies as well as old ones not well known outside their specific fields can and are picked up, transmitted and pollinated across new fields with incredibly rapidity within this subculture.

__Ideaological sharing.__ Ideaologies within the developing subculture are floated, debated, evolve and take root. These can include ideaologies around diversity, ethics and robust science (reproducibility amongst others).

__Strategy sharing.__ Shared and devloping concepts around workflows, professionalising software development management techniques and programming norms in parallel with statistical/methodological skill contribute to a more robust workforce with a broader outlook, doing better, faster and more productively.

A number of these R cultural outputs can translate into very substantive economic value simply by the productivity increases they engender for such a wide group users. They may seem prosaic, but because of the number of people they can help and apply to, their impacts are extraordinary.

Some of the ideas that have been developed and championed in the R community include:

__Visualisation.__ While `ggplot2` owing to Wickham (2009) is possibly the most well known example, the base graphics functionality of R (R Core Team, 2017) helped create a new environment where visualisation was a key factor in the two critical components of creating value: the _finding_ and _communication_ of insights. However, the contribution of the subculture does not start and finish with provision of utilities. Critical to the usage of those utilities is the development of modes of usage and educating the developing subculture as to their value. Critical contributions to this field include the work of Cook (see for a few examples, Unwin, Hofman and Cook (2013), Cook, Lee and Majumder (2016) amongst many others), also ############################





    * workflows. examples from mundane/minor/obvious to some Rachel Meager's [advice on filenames](https://twitter.com/economeager/status/997077103483981825), this gets propagated through the community regularly and never fails to pick up many who never heard it before. To Jenny Bryan's tour de force on workflows. Cite googlesheets, readxl, happy git with R etc.
    * interoperability - two groups: talk to other languages, read other data. [Ursa](http://wesmckinney.com/blog/announcing-ursalabs/), reticulate, rJava, rcpp, tabulizer
    * documentation importance- increase the use of these tools for everybody. Understanding that documentation that works for _me_ doesn't work for everyone. Blog posts, _emojis_ all of these are critical tools for communication. Break down barriers!
    
- Not the only things that are important, but these four prosaic things have had a profound impact on the way we work and will continue to work into the future. in an industry/group of people that are providing leadership into the future it's profoundly influential. Truly decentralising a workforce. 

Important to remember no subculture exists or works in isolation.

Influenced from the outside, but even a relatively small one can influence right back. That's what R is doing.




    
[Differences promote ecological robustness](https://mobile.twitter.com/hrbrmstr/status/997485070100451328/photo/1) ERUM 2018, roger bivand. [Get talk notes here for research](https://github.com/rsbivand/eRum18)




# With subculture comes _values_

OUTLINE:

- A subculture transmits not just _ideas_ but _ideaology_.

- A unique place in time and in our broader super culture for data nerds right now.
- Unique place for data nerds in history - we are influential, we are able to exert power on the way our world is changing. We are able to provide a nuanced view as a comnmunity. The power of a subsculture is that you can have multiple diverging view points about a single thing.

- As a subculture we are aware of both the _value_ of the new, as well as the need for _values_ to utilise the new fairly. 

    * Can explore the confluence of consequences. E.g. [building code to kill people](https://twitter.com/stephaniecodes/media), as expressed by Caleb Thompson and drawn by Stephanie Nemeth.
    * Data values, e.g. [data based policing](https://www.economist.com/news/britain/21742151-over-third-those-named-it-have-no-serious-convictions-database-suspected-london?frsc=dg%7Ce) [and the corollary in the US from the subculture](https://twitter.com/defsophiaray/status/996151795629125633) @defsophiaray - python user!.


- R as a subclulture transmits _value_, but it also transmits its _values_:

    * A place for new people
    * open source
    * diversity and difference
    * ethics
    * reproducibility
    
The value of this outside the subculture has a strong historic precedent, c.f. Coleman again and again:
    - G. Coleman: _By turning Linux and open source into household names, many more people learned about not just open source but also the ethical foundations—sharing, freedom, and collaboration—of free software production. In other words, historical outcomes proved to be more unpredictable, complex, and ultimately ironic than anyone could have ever imagined._
    - G. Coleman: _Over ten years of active development and use of free software, a critical mass of hackers had inculcated not simply a commitment to their craft but also a well-developed ethos for information freedom and sharing that ran aground against developments in intellectual property law._

- But this is not a homogeneous world view. It's one that comes with a certain level of unavoidable friction.
    - G. Coleman: _Over ten years of active development and use of free software, a critical mass of hackers had inculcated not simply a commitment to their craft but also a well-developed ethos for information freedom and sharing that ran aground against developments in intellectual property law._
    - _"Once we recognize the intimate connection between hacker ethics and liberal commitments and the diversity of ethical positions, it is clear that hackers provide less of a unitary and distinguishable ethical position, and more of a mosaic of interconnected, but at times divergent, ethical principles."_ from "Coding Freedom: The Ethics and Aesthetics of Hacking" by E. Gabriella Coleman

http://amzn.asia/8NAg14E

≈

- We have to decide which values matter to us, which ones will be put out to the world.
- There is no opt-out, they're there whether we acnknowledge them or not. 
- We should debate rigorously amongst ourselves the impacts of our work outside our little life world that's R
0 * life world: technical term.
- We should also think deeply and talk about how we want to shape this lifeworld.



Coleman: _Guiding this practice is the idea that the free software project represents an endeavor that far exceeds any single person’s efforts, and thus everyone’s contribution is highly regarded, whether it involves filing a bug report or offering a significant, large-scale innovation._

Coleman: _On the other hand, hackers often express a commitment to self-reliance, which can be at times displayed in a quite abrasive and elitist tone. The most famous token of this stance is the short quip “Read the Fucking Manual” (RTFM)._

Coleman: _Unlike academics—who at times religiously guard their data or findings until published, or only circulate them among a small group of trusted peers—hackers freely share their findings, insights, and solutions._


# Beyond syntax, conclusion

# References


Anheier, Helmut K., Stefan Toepler and Regina List, eds., (2010): _International Encyclopedia of Civil Society_, Springer New York.

Averick, M. and Meeks, E., (2017): _Beyond the Tip: A data-driven exploration of Archer_, <https://archervisualization.herokuapp.com>, accessed 18/05/21.

Bocek, M., (2018): _Data Science Course in a Box_, <https://github.com/rstudio-education/datascience-box>, accessed 18/05/21.

Coleman, E.G., (2012): _Coding Freedom: The Ethics and Aesthetics of Hacking_, Princeton University Press, Princeton.

Cook, D., Lee, E-K., Majumder, M. (2016): "Data visualization and statistical graphics in big data analysis"," _Annual Review of Statistics and Its Application_, Volume 3, p. 133-159, <https://www.annualreviews.org/doi/10.1146/annurev-statistics-041715-033420>, accessed 18/05/22. 

Ellis, S.E., (2017): "Hey! You there! You are welcome here", _ROpenSci_, <https://ropensci.org/blog/2017/06/23/community/>, accessed 18/05/21.

Hodkinson, P., (2012): Beyond Spectacular Specifics in the Study of Youth (Sub)Cultures, _Journal of Youth Studies_, Volume 15, Issue 5. 

Holtz, Y., (2018): _The R Graph Gallery_ <https://www.r-graph-gallery.com>, accessed 18/05/21.

Ihaka, R., (1998): _R: Past and Future History_, <https://www.stat.auckland.ac.nz/~ihaka/downloads/Interface98.pdf>, accessed 18/05/21.

Maegan, J., (2018): _R4DS: the next iteration_, <https://www.jessemaegan.com/post/r4ds-the-next-iteration/>, acccessed 18/05/21.

R Core Team, (2017): _R: A Language and Environment for Statistical Computing_, R Foundation for Statistical Computing, Vienna.

Robinson, D., (2016): "Text analysis of Trump's tweets confirms he writes only the (angrier) Android half", _Variance Explained_, <http://varianceexplained.org/r/trump-tweets/>, accessed 18/05/21.

Robinson, D., (2017): "Trump's Android and iPhone tweets, one year later", _Variance Explained_, <http://varianceexplained.org/r/trump-followup/>, accessed 18/05/21.

Silge, J., (2017): _Navigating the R Package Universe_, <https://juliasilge.com/blog/navigating-packages/>, acccessed 18/05/21.

Unwin, A., Hofmann, H., Cook, D., (2013): Let graphics tell the story - datasets in R, _The R Journal_, Volume 5, Issue 1, p. 117-129. <https://journal.r-project.org/archive/2013/RJ-2013-012/RJ-2013-012.pdf>, accessed 18/05/22.

Wickham, H., (2009): _ggplot2: Elegant Graphics for Data Analysis_, Springer-Verlag New York.

Wickham, H., (2010): "A Layered Grammar of Graphics", _Journal of Computational and Graphical Statistics_, Volume 19, Number 1, p. 3 - 28.

Wickham, H., Francois, R., Henry, L., Müller, K. (2017): _dplyr: A Grammar of Data Manipulation_, R package version 0.7.4, <https://CRAN.R-project.org/package=dplyr>.

Woo, K., Mudrak, E., _Accidental aRt_, <http://accidental-art.tumblr.com>, accessed 18/05/21.

Yau, N., (2018): _Flowing Data_, <http://flowingdata.com>, accessed 18/05/21.
