---
title: CV
author: Steph de Silva
date: '2018-04-26'
slug: cv
categories:
  - General
tags:
  - Consulting
---

# Summary

An experienced data scientist with a diverse background and a strong technical skill set, I have experience working both internationally and domestically in industries such as development, telecommunications and finance.

A keen statistical programmer, I will be a keynote speaker at the useR! conference in Brisbane in July 2018. 

# Education

__Master of Computer Science (Current)__

I’m currently exploring forecasting in high dimensional data sets and exploring whether agent-based (AI) approaches can provide a robust method of managing massive numbers of time series with a view to submitting a masters’ thesis on the topic.

__Doctor of Philosophy 2004-2008__

Research focused on finding practical, but theoretically robust solutions for testing complex time series models over multiple dimensions (panel data).

__Bachelor of Arts/Commerce 1998-2003__

Honours in Econometrics (first class – game theory). Additional majors in Economics, Latin and Ancient History.

#Work Experience

__Data Science Consultant and Strategist__

_Rex Analytics  /  2014 - 2018_

At Rex Analytics, we provided the missing link for companies with a data focus, but still developing a deep data expertise. Some (but not all) of the projects I worked on include:

    * The Connecting Regional Communities Program, providing advice, analysis and visualization to the Victorian Government around digitization of regional communities.
    * Workflow by Design, a project with a management consulting firm developing a workflow for a rapidly expanding data science consulting practice.
    * Providing data strategy and insights for a late-stage startup.

__Econometrician__

_Department of Communications and the Arts /  July - December 2016_

As a part of this short term contract I contributed to two projects: the regional telecommunications database and was a co-author on the Chief Economist’s major work on the impacts of digitization on productivity. Using Shiny/R, I designed a user interface which allowed departmental users to generate automated reporting. I also provided data visualisation, time series models and growth statistics for the productivity project. 

__Unit Coordinator/eLearning Advisor__

_Swinburne Online  /  2015 – 2017_

I taught for Swinburne’s MBA and MPA programs in finance and economics, as well undergraduate units such as statistics, marketing and business innovation. I take a team of students of varying abilities through a challenging semester of technical work, building on their skills and confidence. 
I’ve taken courses previously rated by students at 5/10 to greater than 8/10 in a single semester.

In order to get my team through the semester, I build interactive apps, design infographics and deliver online content while having fun with it. One of my favourite hobbies!

__Econometrician__

_The World Bank  /  2012 – 2015_

At the World Bank, I worked with the Pacific education team and was responsible for the management of survey and data analysis, modelling and report writing. I provided support for intervention evaluation design, sample design and implementation, in-country support for teams during data collection and entry. I worked on projects from Laos, Papua New Guinea, Tonga, Vanuatu, Timor Leste, Myanmar and Cambodia. 

In 2014, I travelled to Laos to provide statistical support to the Research Institute located in the Ministry of Education in Laos. I co-authored six major World Bank reports and provided statistical/econometric support for many more. In Stata, I developed multi- equation system models for categorical outcomes (classification), including logit, tobit and regression models. Power calculations, RCT evaluation/design, and probabilistic sampling and testing were also in my remit. 

__Casual Lecturer, Associate Lecturer, Research Assistant__

_The University of Sydney  /  2004 – 2009_

I taught and researched advanced data science concepts such as time series modelling and forecasting, classification models, probabilistic theory, applied econometrics and data analysis. 


# Technical Skills

My preferred languages right now: R, Python, Java.

Languages/platforms I’ve worked in previously or have experience with: SQL, Fortran, Gauss, Stata, SPSS, HTML/CSS, Javascript.

# Pro Bono/Community Work 

Cofounder: R-Ladies Remote

Organiser: R-Ladies Sydney

I ran a Code Club from 2017- mid 2018 for a small rural school in Northern NSW. To put this into perspective for you, it was like running a dev team of 20 hyperactive squirrels. Other exciting parts included the time a kid bought a whole jar of spiders to class. Once, a kid bought in a baby rat they found. 

It was the country, what can I tell you? The internet was dreadful, but the wildlife and the people are superb.

#Language Skills

I have a degree in Classical Latin. There are two things about this that are relevant to data science/consulting:

(1) I'm great with communication and language
(2) One day the Vatican will require some kind of analytics _and it will be my moment._



